name: llm-app
base: core22
version: '0.1'
summary: A web-app running ChatGPT locally
description: |
  A web-app using streamlit which serves as a UI to ChatGPT via langchain and the OpenAI API.
  The app is meant as a budget-friendly way of using GPT-4, as well as allowing the user to use the model in several other ways.
  This includes document question answering (TODO), writing/running Python code, browsing Google/Bing etc.
grade: devel  # Use 'stable' for production apps
confinement: devmode #strict  # or 'classic' for apps that require more system access

architectures:
  - build-on: arm64

apps:
  chatgpt-app:
    command: start.sh  # Replace 'app.py' with your Streamlit app's main script if different
    daemon: simple
    plugs: [network, network-bind, removable-media]

parts:
  chatgpt-app:
    plugin: python
    source: .  # This assumes the snapcraft.yaml is in the root of your app directory
    build-packages:
      - python3-pip
      - python3-setuptools
    stage-packages:
      - python3

    # Specify your Python dependencies
    python-packages:
      - chromadb==0.4.3
      - langchain==0.0.237
      - openai==0.27.8
      - pypdf==3.13.0
      - streamlit==1.24.1
      - tiktoken==0.4.0
      - wikipedia==1.4.0
      - streamlit_authenticator

    override-build: |
      cp start.sh $SNAPCRAFT_PART_INSTALL/
      cp *.py $SNAPCRAFT_PART_INSTALL/
      cp -r pages $SNAPCRAFT_PART_INSTALL/
      chmod 755 $SNAPCRAFT_PART_INSTALL/start.sh
      snapcraftctl build

  # Or make a part that runs the app.